### PR TITLE
Update http-proxy-agent

### PR DESCRIPTION
**Pull request by mearleycf**
Version @2.2.1 is vulnerable to machine in the middle attacks, https://www.npmjs.com/advisories/1184
Please update to 3.0.0 or greater.

### CODE REVIEW

**Comment by kartsims** [comment]
Thanks for the heads up

The build is [failing](https://travis-ci.org/TooTallNate/node-https-proxy-agent) on the current versin of `node-https-proxy-agent`.

Also the major version has been bumped, did you check if there are breaking changes in its API before submitting the PR?

**Comment by statianzo** [comment]
Looks like Travis is set up to only set `BROWSERSTACK_KEY` and `BROWSERSTACK_USERNAME` on the master branch. I see this step in the latest master CI logs:

image

But in the PR, there's a warning about them being removed for security reasons

image


As for the major version change, it's due to `node-https-proxy-agent` dropping node 4, 5, and 7 from Travis.

> This release fixes the MitM vulnerability reported via HackerOne. It is a breaking change because Node 4, 5, and 7 are no longer tested in CI (note that Node 6 is still supported).

https://github.com/TooTallNate/node-https-proxy-agent/releases/tag/3.0.0

**Comment by XhmikosR** [comment]
Fixes #66

**Comment by XhmikosR** [comment]
The bad news is that this will need to be a major version change due to the Node.js < 8 drop.

**Comment by XhmikosR** [comment]
But perhaps this is fixed soon https://github.com/TooTallNate/node-https-proxy-agent/issues/84

**Comment by XhmikosR** [comment]
Actually it seems they have released a v2.0.3, so this isn't needed

```
C:\Users\xmr\Desktop\bootstrap>npm ls https-proxy-agent
bootstrap@4.3.1 C:\Users\xmr\Desktop\bootstrap
+-- karma-browserstack-launcher@1.4.0
| +-- browserstack@1.5.3
| | `-- https-proxy-agent@2.2.3
| `-- browserstacktunnel-wrapper@2.0.4
|   `-- https-proxy-agent@2.2.3  deduped
`-- linkinator@1.6.0
  `-- gaxios@2.1.0
    `-- https-proxy-agent@3.0.0
```

So we should be OK. It's just that 2.2.3 isn't detected as having the fix yet.

**Comment by statianzo** [comment]
https-proxy-agent@2.2.3 is now included in the [unaffected versions](https://www.npmjs.com/advisories/1184/versions).

Like @XhmikosR, I was able to upgrade without changing my `browserstack` version.

**Pull request closed without merging**
